name: Deploy maguna-nestjs-be

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Stop any existing app instance
            pkill node || true

            # Navigate to the app directory
            cd /var/www/maguna-nestjs-be

            # Pull the latest code from the repository
            git pull origin main

            # Install dependencies
            npm install

            # Build the application
            npm run build

            # Start the application
            npm run start:prod

            exit
          EOF
