name: Deploy maguna-nestjs-be

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Debug Environment Variables
        run: printenv

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Ensure required packages are installed
            sudo yum install -y git
            sudo yum install -y nodejs npm

            # Create the app directory if it doesn't exist
            sudo mkdir -p /var/www/maguna-nestjs-be
            sudo chown ec2-user:ec2-user /var/www/maguna-nestjs-be

            # Navigate to the app directory
            cd /var/www/maguna-nestjs-be/maguna-nestjs-be

            # Stop any existing app instance
            pkill node || true

            # Pull the latest code from the repository
            git pull origin main || git clone ${{ secrets.REPO_URL }} .

            # Copy the .env file from the secrets
            echo "${{ secrets.ENV_FILE }}" > .env

            # Install dependencies
            npm install

            # Build the application
            npm run build

            # Start the application
            npm run start:prod

            exit
          EOF
